inherits = "ayu_dark"

"type" = "blue"
"type.builtin" = "blue"
"constructor" = "function"
"constant" = "purple"
"constant.numeric" = "purple"
"string" = "green"
"string.regexp" = "teal"
"comment" = { fg = "muted", modifiers = ["italic"] }
"variable" = "foreground"
"label" = "function"
"punctuation" = "foreground"
"keyword" = "orange"
"operator" = "operator"
"function" = "function"
"tag" = "indigo"
"namespace" = "blue"
"markup.heading" = "green"
"markup.list" = "function"
"markup.raw" = "operator"
"markup.link.url" = "muted"
"markup.link.text" = "indigo"
"markup.link.label" = "green"
"markup.quote" = "teal"

[palette]
background = "#0b0e14"
foreground = "#bfbdb6"
black = "#131721"
blue = "#59c2ff"
indigo = "#39bae6"
muted = "#5a6673"
green = "#aad94c"
purple = "#d2a6ff"
orange = "#ff8f40"
red = "#f07178"
teal = "#95e6cb"
yellow = "#e6b450"
function = "#ffb454"
operator = "#f29668"
