#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$REPO_ROOT/scripts/platform.sh"

ORIGINAL_PATH="$PATH"
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:$PATH"

missing=0
for command_name in \
  bat bazelisk brew btop cargo cargo-binstall crit delta dex difft dust emacs htop \
  hunkdiff hx jj jq mosh node npm nu pi rg ruby rust-code-analysis-cli rustup uv \
  zellij zig; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "[ERROR] Missing command: $command_name" >&2
    missing=1
  fi
done

for target in \
  "$HOME/.local/bin/dot" \
  "$HOME/.local/bin/magit" \
  "$HOME/.local/bin/agent-loop" \
  "$HOME/.pi/agent/AGENTS.md" \
  "$HOME/.pi/agent/settings.json" \
  "$HOME/.pi/agent/packages/pi-deep-work/package.json" \
  "$HOME/.claude/CLAUDE.md" \
  "$HOME/.emacs.d/init.el" \
  "$CONFIG_HOME/bat/themes/ayu-dark.tmTheme" \
  "$CONFIG_HOME/git/ignore" \
  "$CONFIG_HOME/git/delta.gitconfig" \
  "$CONFIG_HOME/helix/config.toml" \
  "$CONFIG_HOME/hunk/extensions/reviewed-files/index.tsx" \
  "$NUSHELL_HOME/config.nu" \
  "$NUSHELL_HOME/env.nu" \
  "$ZELLIJ_HOME/config.kdl.tmpl" \
  "$ZELLIJ_HOME/themes/ayu-dark-flat.kdl"; do
  if [[ ! -L "$target" ]]; then
    echo "[ERROR] Expected managed link: $target" >&2
    missing=1
  fi
done

zellij_config="$ZELLIJ_HOME/config.kdl"
zellij_config_marker="// Generated by dot link from config.kdl.tmpl."
if [[ ! -f "$zellij_config" || -L "$zellij_config" ]]; then
  echo "[ERROR] Expected generated file: $zellij_config" >&2
  missing=1
elif [[ "$(head -n 1 "$zellij_config")" != "$zellij_config_marker" ]]; then
  echo "[ERROR] Zellij config is not owned by dot link: $zellij_config" >&2
  missing=1
elif grep -Fq '__ZELLIJ_LABEL' "$zellij_config"; then
  echo "[ERROR] Zellij config contains unresolved label placeholders" >&2
  missing=1
fi

if [[ "$(uname -s)" == Darwin && ! -L "$CONFIG_HOME/ghostty/config" ]]; then
  echo "[ERROR] Expected managed link: $CONFIG_HOME/ghostty/config" >&2
  missing=1
fi

if ! zellij_check="$(zellij setup --check 2>&1)"; then
  echo "[ERROR] Zellij rejected its managed configuration" >&2
  missing=1
elif [[ "$zellij_check" != *"[LOOKING FOR CONFIG FILE FROM]: \"$ZELLIJ_HOME/config.kdl\""* ]]; then
  echo "[ERROR] Zellij is not reading $ZELLIJ_HOME/config.kdl" >&2
  missing=1
fi

if ! bat --list-themes | grep -Fxq 'ayu-dark'; then
  echo "[ERROR] Bat cannot find the ayu-dark syntax theme" >&2
  missing=1
fi

if ! delta --list-syntax-themes | grep -Eq '(^|[[:space:]])ayu-dark$'; then
  echo "[ERROR] Delta cannot find the ayu-dark syntax theme" >&2
  missing=1
fi

if [[ ":$ORIGINAL_PATH:" != *":$HOME/.local/bin:"* ]]; then
  echo "[WARN] Add $HOME/.local/bin to your shell PATH"
fi

if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

echo "[INFO] dotfiles is healthy"
